### ISSUE TITLE
Request to https://api.basetool.io/api/docker/install failed when starting basetool

### ISSUE THREAD

**Issue by ncc-social** [basetool-io/basetool#278]
When I run `docker-compose up`, this is the response I get

```
Starting basetool_redis_1 ... done
Recreating basetool_app_1 ... done
Attaching to basetool_redis_1, basetool_app_1
redis_1  | 1:C 29 Nov 2021 22:29:24.191 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 29 Nov 2021 22:29:24.191 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 29 Nov 2021 22:29:24.191 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 29 Nov 2021 22:29:24.192 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 29 Nov 2021 22:29:24.192 * Running mode=standalone, port=6379.
redis_1  | 1:M 29 Nov 2021 22:29:24.192 # Server initialized
redis_1  | 1:M 29 Nov 2021 22:29:24.193 * Ready to accept connections
app_1    | yarn run v1.22.15
app_1    | $ zx ./scripts/docker-start.mjs && yarn start
app_1    | $ yarn prisma migrate deploy
app_1    | $ /app/node_modules/.bin/prisma migrate deploy
app_1    | (node:30) UnhandledPromiseRejectionWarning: FetchError: request to https://api.basetool.io/api/docker/install failed, reason: Hostname/IP does not match certificate's altnames: Host: api.basetool.io. is not in the cert's altnames: DNS:api-proxy.basetool.io
app_1    |     at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)
app_1    |     at ClientRequest.emit (events.js:400:28)
app_1    |     at TLSSocket.socketErrorListener (_http_client.js:475:9)
app_1    |     at TLSSocket.emit (events.js:400:28)
app_1    |     at emitErrorNT (internal/streams/destroy.js:106:8)
app_1    |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
app_1    |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
app_1    | (Use `node --trace-warnings ...` to show where the warning was created)
app_1    | (node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
app_1    | (node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
app_1    | Prisma schema loaded from prisma/schema.prisma
app_1    | Datasource "db": PostgreSQL database "basetool", schema "public" at "host.docker.internal:5432"
app_1    | 
app_1    | 29 migrations found in prisma/migrations
app_1    | 
app_1    | No pending migrations to apply.
app_1    | $ next start
app_1    | ready - started server on 0.0.0.0:7654, url: http://localhost:7654
```

When I access `http://localhost:7654`, a 404 page is displayed

After this, I tried going to `https://api.basetool.io` directly, this is what I get:

![image](https://user-images.githubusercontent.com/78477962/143954316-9e1ffd01-716d-48fa-945c-edc21b68e576.png)

I am testing this on Docker Desktop v4.2.0 (70708) on a MacOS Catalina and Chrome Browser v96.0.4664.55 (Official Build)

**Comment by adrianthedev** [comment]
Hey @ncc-social,

Apologies for the `api.basetool.io` error. We should have handled that more gracefully. We fixed that in the meantime.
Also, that's only telemetry so that shouldn't affect the way the app works.

Regarding the app not working, I tested the docker image this morning and worked on my end. Let's try and troubleshoot together.
Could you please re-download the `docker-compose.yml` and `.env` files and try again? We tweaked the configuration.
Also, let's try to use another port to see if that's the issue.

Ex: let's say you want to use `11223`. You need to update the `PORT` in `.env` (`PORT=11223`) and in the `docker-compose.yml` file and then try accessing `http://localhost:11223`.

If that won't fix it, please leave the console output here to see if we can see anything wrong.

```diff
# docker-compoe.yml
version: "3.9"

services:
  app:
    build: .
    env_file: .env
    image: docker.io/library/basetool
    ports:
--      - "7654:7654"
++      - "11223:11223"
    links:
      - redis
  redis:
    image: redis
```

**Comment by ncc-social** [comment]
I started by 
`curl -LO https://raw.githubusercontent.com/basetool-io/basetool/main/deploy/docker/docker-compose.yml`
`curl -LO https://raw.githubusercontent.com/basetool-io/basetool/main/deploy/docker/.env.sample`
`mv .env.sample .env`

`DATABASE_URL=postgresql://johnsmith:johnsmith@host.docker.internal/basetool`

`docker-compose up`

```
johnsmith@myMac basetool % curl -LO https://raw.githubusercontent.com/basetool-io/basetool/main/deploy/docker/docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    298      0 --:--:-- --:--:-- --:--:--   298
johnsmith@myMac basetool % curl -LO https://raw.githubusercontent.com/basetool-io/basetool/main/deploy/docker/.env.sample
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1465  100  1465    0     0   2267      0 --:--:-- --:--:-- --:--:--  2264
johnsmith@myMac basetool % mv .env.sample .env
johnsmith@myMac basetool % openssl rand -hex 32
bb741b8062566a0e31848ab49b0735a1cb6460b8f9a2aa062688ca89927580f5
johnsmith@myMac basetool % docker-compose up
Building app
[+] Building 2.4s (12/24)                                                       
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.58kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine          2.1s
 => [auth] library/node:pull token for registry-1.docker.io                0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 8.26kB                                        0.0s
 => [runner  1/11] FROM docker.io/library/node:14-alpine@sha256:240e1e6ef  0.0s
 => CACHED [runner  2/11] WORKDIR /app                                     0.0s
 => [builder 3/5] COPY . .                                                 0.0s
 => CACHED [deps 2/6] RUN apk add --no-cache libc6-compat python3 py3-pip  0.0s
 => CACHED [deps 3/6] WORKDIR /app                                         0.0s
 => ERROR [deps 4/6] COPY package.json yarn.lock ./                        0.0s
 => ERROR [deps 5/6] COPY prisma ./                                        0.0s
------
 > [deps 4/6] COPY package.json yarn.lock ./:
------
------
 > [deps 5/6] COPY prisma ./:
------
failed to compute cache key: "/prisma" not found: not found
ERROR: Service 'app' failed to build : Build failed
```
I started creating the folders myself as and when it requests for it. This is the final output and I still get a 404 page.
I currently do not have any files in the pages folder

```
johnsmith@myMac basetool % docker-compose up --build
Building app
[+] Building 306.5s (25/25) FINISHED                                            
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 84B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine          2.1s
 => [auth] library/node:pull token for registry-1.docker.io                0.0s
 => [runner  1/11] FROM docker.io/library/node:14-alpine@sha256:240e1e6ef  0.0s
 => [internal] load build context                                          8.2s
 => => transferring context: 4.98MB                                        7.9s
 => CACHED [runner  2/11] WORKDIR /app                                     0.0s
 => [builder 3/5] COPY . .                                                19.2s
 => CACHED [deps 2/6] RUN apk add --no-cache libc6-compat python3 py3-pip  0.0s
 => CACHED [deps 3/6] WORKDIR /app                                         0.0s
 => CACHED [deps 4/6] COPY package.json yarn.lock ./                       0.0s
 => CACHED [deps 5/6] COPY prisma ./                                       0.0s
 => CACHED [deps 6/6] RUN yarn install --frozen-lockfile                   0.0s
 => [builder 4/5] COPY --from=deps /app/node_modules ./node_modules       30.2s
 => [builder 5/5] RUN yarn build && yarn install --production --ignore-  167.2s
 => CACHED [runner  3/11] RUN addgroup -g 1001 -S nodejs                   0.0s 
 => CACHED [runner  4/11] RUN adduser -S nextjs -u 1001                    0.0s 
 => CACHED [runner  5/11] COPY --from=builder /app/next.config.js ./       0.0s 
 => CACHED [runner  6/11] COPY --from=builder /app/public ./public         0.0s 
 => CACHED [runner  7/11] COPY --from=builder /app/prisma ./prisma         0.0s
 => CACHED [runner  8/11] COPY --from=builder /app/scripts ./scripts       0.0s
 => [runner  9/11] COPY --from=builder --chown=nextjs:nodejs /app/.next .  0.1s
 => [runner 10/11] COPY --from=builder /app/node_modules ./node_modules   26.8s
 => [runner 11/11] COPY --from=builder /app/package.json ./package.json    0.1s
 => exporting to image                                                    25.2s
 => => exporting layers                                                   25.2s
 => => writing image sha256:bb64c189a5c03e1514f4a9f647d134206f3f583c53bc4  0.0s
 => => naming to docker.io/library/basetool                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Creating basetool_redis_1 ... done
Creating basetool_app_1   ... done
Attaching to basetool_redis_1, basetool_app_1
redis_1  | 1:C 30 Nov 2021 17:15:01.602 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 30 Nov 2021 17:15:01.602 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 30 Nov 2021 17:15:01.602 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 30 Nov 2021 17:15:01.603 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 30 Nov 2021 17:15:01.605 * Running mode=standalone, port=6379.
redis_1  | 1:M 30 Nov 2021 17:15:01.605 # Server initialized
redis_1  | 1:M 30 Nov 2021 17:15:01.606 * Ready to accept connections
app_1    | yarn run v1.22.15
app_1    | $ zx ./scripts/docker-start.mjs && yarn start
app_1    | $ yarn prisma migrate deploy
app_1    | $ /app/node_modules/.bin/prisma migrate deploy
app_1    | Prisma schema loaded from prisma/schema.prisma
app_1    | Datasource "db": PostgreSQL database "basetool", schema "public" at "host.docker.internal:5432"
app_1    | 
app_1    | 29 migrations found in prisma/migrations
app_1    | 
app_1    | No pending migrations to apply.
app_1    | $ next start
app_1    | ready - started server on 0.0.0.0:11223, url: http://localhost:11223
```

```
johnsmith@myMac basetool % docker-compose up        
Starting basetool_redis_1 ... done
Starting basetool_app_1   ... done
Attaching to basetool_redis_1, basetool_app_1
redis_1  | 1:C 30 Nov 2021 17:26:15.668 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 30 Nov 2021 17:26:15.668 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 30 Nov 2021 17:26:15.668 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 30 Nov 2021 17:26:15.669 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 30 Nov 2021 17:26:15.670 * Running mode=standalone, port=6379.
redis_1  | 1:M 30 Nov 2021 17:26:15.670 # Server initialized
redis_1  | 1:M 30 Nov 2021 17:26:15.671 * Ready to accept connections
app_1    | yarn run v1.22.15
app_1    | $ zx ./scripts/docker-start.mjs && yarn start
app_1    | $ yarn prisma migrate deploy
app_1    | $ /app/node_modules/.bin/prisma migrate deploy
app_1    | Prisma schema loaded from prisma/schema.prisma
app_1    | Datasource "db": PostgreSQL database "basetool", schema "public" at "host.docker.internal:5432"
app_1    | 
app_1    | 29 migrations found in prisma/migrations
app_1    | 
app_1    | No pending migrations to apply.
app_1    | ┌─────────────────────────────────────────────────────────┐
app_1    | │  Update available 3.1.1 -> 3.6.0                        │
app_1    | │  Run the following to update                            │
app_1    | │    yarn add --dev prisma@latest                         │
app_1    | │    yarn add @prisma/client@latest                       │
app_1    | └─────────────────────────────────────────────────────────┘
app_1    | $ next start
app_1    | ready - started server on 0.0.0.0:11223, url: http://localhost:11223
```

**Comment by adrianthedev** [comment]
This is good feedback. Let me try and reproduce it. Thank you!

**Comment by adrianthedev** [comment]
To give you a bit more context, it shouldn't ask for those directories. It should just pull the image and run.

**Comment by adrianthedev** [comment]
@ncc-social can you try this `docker compose.yml` config? Please be aware the port is `7654` for this config. you can change it to anything else.

```
version: "3.9"

services:
  app:
    image: docker.io/basetool/basetool:latest
    env_file: .env
    ports:
      - "7654:7654"
    links:
      - redis
  redis:
    image: redis
```

**Comment by ncc-social** [comment]
> @ncc-social can you try this `docker compose.yml` config? Please be aware the port is `7654` for this config. you can change it to anything else.
> 
> ```
> version: "3.9"
> 
> services:
>   app:
>     image: docker.io/basetool/basetool:latest
>     env_file: .env
>     ports:
>       - "7654:7654"
>     links:
>       - redis
>   redis:
>     image: redis
> ```

I am happy to report I have my login page after using the above `docker-compose.yml`
```
johnsmith@myMac basetool % docker-compose up
Creating network "basetool_default" with the default driver
Pulling app (docker.io/basetool/basetool:latest)...
latest: Pulling from basetool/basetool
97518928ae5f: Already exists
c7746cfd346e: Already exists
d06092bf767c: Already exists
dc1629f1d922: Already exists
2c0d81569a1c: Pull complete
7a49108340a7: Pull complete
60729f5364b9: Pull complete
957a872b3ef7: Pull complete
eabab1127161: Pull complete
0b2d768d12e1: Pull complete
517167223b3f: Pull complete
bdd333ae572b: Pull complete
731f099bca0b: Pull complete
4f86fa028e9a: Pull complete
Digest: sha256:a19d98d5725217507b607d41f93592d26f9e741184e8586f9ac55fb6fbb05d28
Status: Downloaded newer image for basetool/basetool:latest
Creating basetool_redis_1 ... done
Creating basetool_app_1   ... done
Attaching to basetool_redis_1, basetool_app_1
redis_1  | 1:C 30 Nov 2021 20:23:48.311 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 30 Nov 2021 20:23:48.311 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 30 Nov 2021 20:23:48.311 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 30 Nov 2021 20:23:48.312 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 30 Nov 2021 20:23:48.313 * Running mode=standalone, port=6379.
redis_1  | 1:M 30 Nov 2021 20:23:48.313 # Server initialized
redis_1  | 1:M 30 Nov 2021 20:23:48.314 * Ready to accept connections
app_1    | yarn run v1.22.15
app_1    | $ zx ./scripts/docker-start.mjs && yarn start
app_1    | $ yarn prisma migrate deploy
app_1    | $ /app/node_modules/.bin/prisma migrate deploy
app_1    | Prisma schema loaded from prisma/schema.prisma
app_1    | Datasource "db": PostgreSQL database "basetool", schema "public" at "host.docker.internal:5432"
app_1    | 
app_1    | 29 migrations found in prisma/migrations
app_1    | 
app_1    | No pending migrations to apply.
app_1    | $ next start
app_1    | ready - started server on 0.0.0.0:7654, url: http://localhost:7654
```

![image](https://user-images.githubusercontent.com/78477962/144123744-33505a34-f73f-41a6-9a94-5132c1f9bac2.png)

## Thank you very much for the assistance. Really appreciate it 👍

**Comment by adrianthedev** [comment]
For sure! Thank you for your time!

You should be good to go from this login page. If not, you know where to find me :)
